spring.application.name=procesamiento-asincrono

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/procesamiento_asincrono
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME:app}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:app}

# Actuator
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
